<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12994" started-at="2020-01-26T18:40:55 IST" finished-at="2020-01-26T18:41:08 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12994" started-at="2020-01-26T18:40:55 IST" finished-at="2020-01-26T18:41:08 IST">
      <class name="org.ActiTime.testscripts.CreateCustomer">
        <test-method status="PASS" signature="OpenBrowser()[pri:0, instance:org.ActiTime.testscripts.CreateCustomer@53f65459]" name="OpenBrowser" is-config="true" duration-ms="5132" started-at="2020-01-26T18:40:55 IST" finished-at="2020-01-26T18:41:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenBrowser -->
        <test-method status="PASS" signature="Login()[pri:0, instance:org.ActiTime.testscripts.CreateCustomer@53f65459]" name="Login" is-config="true" duration-ms="436" started-at="2020-01-26T18:41:00 IST" finished-at="2020-01-26T18:41:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="FAIL" signature="testCreateCustomer()[pri:0, instance:org.ActiTime.testscripts.CreateCustomer@53f65459]" name="testCreateCustomer" duration-ms="5179" started-at="2020-01-26T18:41:00 IST" finished-at="2020-01-26T18:41:05 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at org.ActiTime.webpages.AddNewCustomerPage.customerNameTextfield(AddNewCustomerPage.java:30)
at org.ActiTime.testscripts.CreateCustomer.testCreateCustomer(CreateCustomer.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateCustomer -->
        <test-method status="PASS" signature="LogOut()[pri:0, instance:org.ActiTime.testscripts.CreateCustomer@53f65459]" name="LogOut" is-config="true" duration-ms="84" started-at="2020-01-26T18:41:05 IST" finished-at="2020-01-26T18:41:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogOut -->
        <test-method status="PASS" signature="CloseBrowser()[pri:0, instance:org.ActiTime.testscripts.CreateCustomer@53f65459]" name="CloseBrowser" is-config="true" duration-ms="2101" started-at="2020-01-26T18:41:05 IST" finished-at="2020-01-26T18:41:08 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
      </class> <!-- org.ActiTime.testscripts.CreateCustomer -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
